---
title: "Project 1 Data Clean-up"
author: "Erin Shellman"
date: "April 25, 2015"
output:
  html_document:
    theme: readable
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: 2
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE)

require(dplyr)
require(ggplot2)
require(GGally)
require(scales)
require(lubridate)
require(caret)

setwd('~/projects/BI-TECH-CP303/projects/project 1')
usage = read.delim('./data/usage_2012.tsv',
                   sep = '\t',
                   header = TRUE)

stations = read.delim('./data/stations.tsv',
                   sep = '\t',
                   header = TRUE)

weather = read.delim('./data/daily_weather.tsv',
                   sep = '\t',
                   header = TRUE)
```

```{r, eval = FALSE}
library(dplyr)
library(ggplot2)
library(lubridate)

usage = read.delim('usage_2012.tsv',
                   sep = '\t',
                   header = TRUE)

weather = read.delim('daily_weather.tsv',
                   sep = '\t',
                   header = TRUE)

stations = read.delim('stations.tsv',
                   sep = '\t',
                   header = TRUE)
```

We saw how to merge the datasets together into one, but it often makes sense to 
do some aggregation before merging. For example, since we know *usage* needs to 
be aggregated and summarized to remove the date variable, it makes 
sense to merge *usage* with the weather data and summarized before merging on 
the station data.  For example:
```{r}

head(usage)
custs_per_day = 
  usage %>% 
    group_by(time_start = as.Date(time_start), station_start, cust_type) %>% 
    summarize(no_rentals = n(),
              duration_mins = mean(duration_mins, na.rm = TRUE))

head(custs_per_day)

# make sure we have consistent date formats
custs_per_day$time_start = ymd(custs_per_day$time_start)
weather$date = ymd(weather$date)

# we made this data frame in the merging section above
weather_rentals = merge(custs_per_day, weather, 
                        by.x = 'time_start', by.y = 'date')

# group_by all the factors and summarize the continuous variables to generate
# a final data frame that can be merged by station.
model_data = 
  weather_rentals %>% 
    group_by(
      station_start, 
      cust_type,
      weekday, 
      season_code, 
      is_holiday, 
      is_work_day, 
      weather_code) %>% 
    summarize(
      rentals = mean(no_rentals),
      duration = mean(duration_mins),
      temp = mean(temp),
      subjective_temp = mean(subjective_temp),
      humidity = mean(humidity),
      windspeed = mean(windspeed))

head(model_data)
   
# now merge on stations
final_data = merge(model_data, stations, 
  by.x = 'station_start',
  by.y = 'station')
  
data = final_data
rm(final_data)

# remove variables from the data that won't be used for modeling, e.g. lat/long
data_to_model = 
  data %>%
    select(-station_start, -id, -terminal_name, -lat, -long)

dim(data_to_model)
head(data_to_model)

model = lm(rentals ~ ., data = data_to_model)
summary(model)

# hmm, we have some weirdness in there, some stations features don't exist 
# around any of our stations, e.g. 'turning_loop'
table(data_to_model$turning_loop)

# lets remove those using the handly 'colSums' and 'which' functions
colSums(data_to_model[ , 15:143])

# we want to know 'which' columns have a sum of 0
columns_to_remove = names(which(colSums(data_to_model[ , 15:143]) == 0))

# now combine that with filter to remove those from our data
data_to_model = data_to_model[ , !(names(data_to_model) %in% columns_to_remove)]

# try the model again
model = lm(rentals ~ ., data = data_to_model)  
summary(model)

# definintely better, but we still have some weird NAs, lets troubleshoot those
table(data_to_model$vending_machine)
table(data_to_model$storage)
table(data_to_model$dojo)
table(data_to_model$tax_service)
table(data_to_model$telephone)

# all the landmarks have at most 1 in the area, so there are not enough 
# observations for least square to fit the model.
# these variables won't be helpful in prediction, so lets remove them.

data_to_model = 
  data_to_model %>% 
  select(
    -vending_machine, 
    -storage,
    -dojo,
    -tax_service,
    -telephone)
    
# try the model again
model = lm(rentals ~ ., data = data_to_model)  
summary(model)

# one last modification. our categorical variables are being treated like 
# they're continuous. lets create some factors
data_to_model$weekday = factor(data_to_model$weekday, 
                               labels = 0:6, 
                               levels = 0:6)
data_to_model$season_code = factor(data_to_model$season_code)
data_to_model$is_holiday = factor(data_to_model$is_holiday)
data_to_model$is_work_day = factor(data_to_model$is_work_day)
data_to_model$weather_code = factor(data_to_model$weather_code)

# try the model again
model = lm(rentals ~ ., data = data_to_model)  
summary(model)

# now 'is_work_day1' is NA, what gives?! remember the assumptions of linear 
# regression. our covariates must be independent - that is, not correlated. in
# this case if you know the values of weekday, you know the value of 
# is_work_day so that assumption doesn't hold. get rid of it!
data_to_model$is_work_day = NULL

# try the model again
model = lm(rentals ~ ., data = data_to_model)  
summary(model)

# ok, we've successfully hit a model but boy does it have a lot of predictors
```